name: Bump version and update theme.toml
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows committing & tagging
  pull-requests: write  # Allows PR creation

jobs:
  build:
    if: github.actor != 'github-actions[bot]'  # Prevent infinite loop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update theme.toml with new version
        run: |
          NEW_VERSION="${{ steps.tag_version.outputs.new_tag }}"
          sed -i "s/^version = .*/version = '${NEW_VERSION}'/" theme.toml

      - name: Commit updated theme.toml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add theme.toml
          git commit -m "Update theme.toml to version ${{ steps.tag_version.outputs.new_tag }}"
          git push origin main

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
